server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bookManagement?serverTimezone=Asia/Seoul
#    username: sungchoon
#    password: sungchoon

#    url: jdbc:mysql://localhost:3305/book_management?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/book_management
#    url: jdbc:mysql://docker-management-server:3306/book_management

    username: sungchoon
    password: qkrtjdcns1!

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    database: mysql

  redis:
    host: localhost
    port: 6379
